### ISSUE TITLE
Counters do not appear

### ISSUE THREAD

**Issue by Hermanest** [Caeden117/CountersPlus#113]
**Bug**
counters do not appear

**Screenshots or Video**
![VirtualDesktop Android-20220106-211513](https://user-images.githubusercontent.com/55062714/148431052-57b9c2ad-decc-4ad1-ab9a-00c6bee02e85.jpg)

**Log**
[_latest.log](https://github.com/Caeden117/CountersPlus/files/7823891/_latest.log)

**Comment by Alaklasm** [comment]
It didn't appear for me either at first. What fixed it for me was messing around with the main canvas in the HUDS tab. **I changed the size and position scale sliders to 10.00 and everything started showing up normally again.** It looks like after the last update all my settings and counters were reset. What I guess happened was because of the reset, the main canvas settings defaulted to have the smallest size and position scale setting, making all the counters I switched on appear behind me (size=1) and smushed together (position scale=1) for some reason.
