### ISSUE TITLE
lag on note hit

### ISSUE THREAD

**Issue by sboys3** [Caeden117/CountersPlus#13]
Every time I hit a note correctly the game drops a few frames while the counters+ plugin is installed

**Comment by Caeden117** [comment]
Hey, please either upload your Counters+ config file, or tell me what counters you have enabled. Often times issues like these can be solved by disabling some counters.

**Comment by sboys3** [comment]
Here is my config file
[CountersPlus.ini.txt](https://github.com/Caeden117/CountersPlus/files/3051185/CountersPlus.ini.txt)

**Comment by Caeden117** [comment]
Seems like what I'd do is go into the Counters+ settings UI and change the Score Counter's `mode` option to Base Game. That'll switch it completely over to what Beat Saber uses, and should help with performance.

If you haven't already, also grab [the latest Counters+ version.](https://github.com/Caeden117/CountersPlus/releases/tag/1.5.3-hotfix1) I'm not sure if this will help if you are already on 1.5.3, but I think it might help if you are using 1.5.2.

**Comment by sboys3** [comment]
[Score] with mode=Both is the most laggy, but even [Notes] is causing some lag when when it is enabled
I already have 1.5.3

**Comment by Yongkykun** [comment]
Hi, I also have the same input lag issue. As well as that, I can't make any changes to the settings. All the buttons are unresponsive. Not quite sure why since it's my very first time using it. Tried restarting the game to no avail as well.

**Comment by Caeden117** [comment]
Hmm. I havent updated to 0.13.2 (I don't know why lmao), give me a few to download and then I can see if anything borked between 0.13.1 and 0.13.2

**Comment by Caeden117** [comment]
Alright. Something happened to CustomUI between 0.13.1 and 0.13.2 that completely broke my stuff. I'm going to contact the people behind it and see if they did anything

**Comment by Yongkykun** [comment]
The only way I can get it to work at the moment is by changing the .ini file directly.

**Comment by Caeden117** [comment]
I've let some of the other modders know about the situation with CustomUI. If they aren't able to fix it (Which, fingers crossed, they will), I'll have to either go back to using the Settings UI (Gross), or come up with another way to handle settings (Time consuming). For now, modifying the `.ini` file is going to be your best friend.

**Comment by sboys3** [comment]
Are the changes with CustomUI responsible for the lag or is it an unrelated problem?

**Comment by Caeden117** [comment]
Nope, however during testing I did not notice any significant frame dips while playing songs. If it helps, [I released a beta build of 1.5.4](https://github.com/Caeden117/CountersPlus/releases/tag/1.5.4-beta1). If it doesn't fix performance issues, my only other suggestion would be to disable counters that you don't really need (Score Counter, Notes, etc.)

**Comment by sboys3** [comment]
I think the lag might be a customUI or TextMeskPro bug.
The lag stops happening when I compile CountersPlus with _scoreMesh.text and other .text commented out in ScoreCounter.cs

**Comment by Caeden117** [comment]
It's probably a TextMeshPro bug then. It could also be the amount of times the text property is being called. On some maps, particularly those with high note density, those are getting modified many times every second. Again, an easy fix for this is to change Score Counters mode to Base Game, or disable it entirely.

Because of the CustomUI situation, I might have to document the CountersPlus ini file, so it'll be easy for people modifying the file.

**Comment by Caeden117** [comment]
Good news, everyone!

It turns out some code was swapped in recent builds of CustomUI, and a quick fork that swapped them back into the right places got Counter+'s UI to work again!

But it didn't really matter, as monkeymanboy is working on a system that should hopefully circumvent this issue. If it persists, then ima be angery.

If you want your Counters+ UI working again, here's a [Fixed CustomUI](https://github.com/Caeden117/CountersPlus/files/3056816/FixedCustomUI.zip) that you can enjoy for now.

**Comment by Yongkykun** [comment]
Thanks for this amazing mod, Caeden117!
