### ISSUE TITLE
Performance concern on CutCounter due to using List<int>.Average()

### ISSUE THREAD

**Issue by Swofty** [Caeden117/CountersPlus#18]
**Describe the Bug**
With the 1.5.7 update, CutCounter has been updated to reuse its old implementation of calling .Average() on a List. This is a potential performance concern on maps with high note count and high note density (e.g. Freedom Dive V2).

Consider:
1) Dynamic arrays can resize at anytime when you call .Add(), which can cause a random performance hit on a single frame.
2) Calling .Average() every note cut results in the game having to sum all the elements on each cut. This runtime will scale with the size of the array O(n), which means it will take longer to process on maps with large number of notes (e.g. Freedom Dive V2). On maps with high note density, cuts are happening very frequently, and this sets up the potential to cause the game to lag or hang.

Instead:
Adding the note score to a running total, and then dividing by total notes cut. This is much faster from a performance perspective, as it runs in O(1) per note hit. Also, it seems unnecessary to keep a running history of the notes cut, as that info is not being used anywhere. (Is there some underlying problem that you are trying to avoid?)

**Attach or Link Files**
https://github.com/Caeden117/CountersPlus/blob/77a869b0dfa3837fe17f084601b35ef9dae083f6/Counters%2B/Counters/CutCounter.cs#L72

Previous version which uses the total score / total cuts method:
https://github.com/Caeden117/CountersPlus/commit/404c7f0564337b61a981202337753388995115a6#diff-ff8dfc2af3bb527e2066351a9e3915d8

**Additional context**

**Comment by Caeden117** [comment]
The original issue with CutCounter's performance was that I forgot to unsubscribe from an event of my own, causing said events to cluster more and more until performance slows (See [this commit.](https://github.com/Caeden117/CountersPlus/commit/b8c7a1e9e2240e94db41988a5e70fc44579eeb66#diff-ff8dfc2af3bb527e2066351a9e3915d8R63)) Figuring that a lot of the performance issues with CutCounter were gone, I reverted back to a list instead of dividing by a total score.

I'll go ahead and accept your pull request. It'll be best to reduce the performance impact of Counters+ as much as possible.
