### ISSUE TITLE
Counters+ progress counter not showing up

### ISSUE THREAD

**Issue by Poulpitor** [Caeden117/CountersPlus#24]
**Describe the Bug**
Hi, 

I'm having trouble with getting the progress ring with time to show up in Counters+. Usually it was under the life bar, but now it's not and I've been unsuccessful in making it show up. Turning on and off any options in the progress tab doesn't do anything when I get into a song. 

**Attach or Link Files**

[CountersPlus - Copie.txt](https://github.com/Caeden117/CountersPlus/files/3464877/CountersPlus.-.Copie.txt)
[2019.08.04.13.43.20.log](https://github.com/Caeden117/CountersPlus/files/3464878/2019.08.04.13.43.20.log)

**Probable Culprit**
No idea. It worked before, but now it doesn't... I've rebooted Beat Saber back to 0 via full uninstall (steam uninstall + folder removal), then put the mods back, to no avail. 

Hope you can find what's up !

**Comment by Caeden117** [comment]
So the problem here is that Progress counter's `Mode` setting is set to an incorrect value. I'd go into more detail about why that might be, but I need to get going real soon.

Here's your fixed CountersPlus config file:

[CountersPlus.txt (Rename this to CountersPlus.ini)](https://github.com/Caeden117/CountersPlus/files/3464891/CountersPlus.txt)

**Comment by Poulpitor** [comment]
Thank you very much !
