### ISSUE TITLE
CounterWarning persists beyond Counters+ settings menu

### ISSUE THREAD

**Issue by Pespiri** [Caeden117/CountersPlus#28]
Top text from Counters+ settings persists after exiting it.

![20190911231257_1](https://user-images.githubusercontent.com/32248439/64735938-d3f49200-d4e9-11e9-8c75-20bb84e24445.jpg)

**Comment by Caeden117** [comment]
Hi,

Due to the arrival of school, the time I have to work on projects have been reduced significantly. A big chunk of my day is taken up by school, plus any stuff I have going on afterwards (Which is usually every Wednesday), and then I juggle the rest of the time before I sleep between school work, ChroMapper, Counters+, and just leisure. Long story short, development is being slowed big time.

For a start, [here is my current Counters+ build.](https://github.com/Caeden117/CountersPlus/files/3603757/CountersPlus.zip) This is essentially up to date with the `bsml-integration` branch, with maybe some uncommitted changes on my end. If the issue persists there, I would know that it is still a current issue and that I need to look into it when I have the time.

**Comment by Caeden117** [comment]
Fixed as of Counters+ `1.7.0`
