### ISSUE TITLE
Counters in demos non functional

### ISSUE THREAD

**Issue by Kakifrucht** [Caeden117/CountersPlus#40]
With the new ScoreSaber updates, many of the counters no longer work during demo replay (average cut, percentage, probably more I haven't tested). If this is something you cannot fix it would be nice if you could disable the non functional counters, instead of them displaying 0.

**Comment by Caeden117** [comment]
Hi,

This appears to be a conflict between Counters+ and ScoreSaber. From what I understand, due to how the recent versions of ScoreSaber now handle replays, everything that is subscribed to internal events are prevented from firing except for events that ScoreSaber itself uses, breaking compatibility with the base game (To prevent unwanted cheating) and Counters+ (Where this issue occurs).

I am unsure if Umbranox would create a "whitelist" of events and whitelist those from Counters+, or if he'd tell me "lol no" and I'd have to disable the non functioning counters.

I've sent a message to him about the issue, and I'll get back to this when he replies.

**Comment by Caeden117** [comment]
Umbranox replied with some other events that Counters+ can subscribe to that will work both in game and during ScoreSaber replays, so I went ahead and swapped some events to those and they now work as expected.

This issue will be fixed for Counters+ 1.8.2.

**Comment by Kakifrucht** [comment]
Great, thank you!
