### ISSUE TITLE
Wrong missed count in replay mode

### ISSUE THREAD

**Issue by claudiodemarzo** [Caeden117/CountersPlus#47]
The "missed notes" counter sometimes registers missed notes when in fact you haven't missed any. I can't understand what makes this error to take place, since it literally happens randomly, and it's also inconsistent throghout various replays (the wrong count takes place in different points of the song). You can find a good example in [this](https://www.youtube.com/watch?v=gspF_b0xHGs) video, where i've actually passed the song with a fc but the missed counter is set to 4 for some reason. This only happens in replay mode.

**Comment by Caeden117** [comment]
Unfortunately this is a problem between Counters+ and ScoreSaber that I cannot easily solve on my end, since during replays ScoreSaber hijacks many core game features that Counters+ relies on with no proper compatibility in mind.

I've contacted Umbranox about potential solutions for this issue but I've received no response. If he does respond with a potential solution then I will gladly look into it. But for now, this cannot be fixed.
